version: '3.9'
services:
  backend:
    build: .
    container_name: pocketbase_devc
    volumes:
      - .:/go/src
    ports:
      - 8090:8090
      - 8089:8089
    expose:
      - 8090
      - 8089
